meta_product_name: "Product Name"
meta_title: "JuxBar - On a tous le droit à notre 1/4h de GLOIRE !!!!"
meta_description: "JuxBar révolutionne le jukebox en vous permettant de prendre le controle de la playlist de votre bar préféré !!!!"
meta_image: "cover.png"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
